### ISSUE TITLE
Race Condition in MongoDbHelper.VerifyCollectionExists

### ISSUE THREAD

**Issue by kalahari** [serilog/serilog-sinks-mongodb#24]
When multiple processes simultaneously execute `MongoDbHelper.VerifyCollectionExists` with the same collection, more than one process may try to create the collection. This results in an unhanded exception:
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> MongoDB.Driver.MongoCommandException: Command create failed: collection already exists.
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.ProcessReply(ConnectionId connectionId, ReplyMessage`1 reply)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](DatabaseNamespace databaseNamespace, BsonDocument command, IElementNameValidator commandValidator, Func`1 responseHandling, Boolean slaveOk, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ServerDescription serverDescription, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelSource channelSource, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.WriteCommandOperation`1.Execute(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CreateCollectionOperation.Execute(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperation[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.ExecuteWriteOperation[T](IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.CreateCollectionHelper[TDocument](String name, CreateCollectionOptions`1 options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.CreateCollection(String name, CreateCollectionOptions options, CancellationToken cancellationToken)
   at Serilog.Helpers.MongoDbHelper.VerifyCollectionExists(IMongoDatabase database, String collectionName, CreateCollectionOptions collectionCreationOptions)
   at Serilog.Sinks.MongoDB.MongoDBSink..ctor(IMongoDatabase database, Nullable`1 batchPostingLimit, Nullable`1 period, IFormatProvider formatProvider, String collectionName, CreateCollectionOptions collectionCreationOptions)
   at Serilog.Sinks.MongoDB.MongoDBSink..ctor(String databaseUrlOrConnStrName, Nullable`1 batchPostingLimit, Nullable`1 period, IFormatProvider formatProvider, String collectionName, CreateCollectionOptions collectionCreationOptions)
   at Serilog.LoggerConfigurationMongoDBExtensions.MongoDB(LoggerSinkConfiguration loggerConfiguration, String databaseUrl, String collectionName, LogEventLevel restrictedToMinimumLevel, Nullable`1 batchPostingLimit, Nullable`1 period, IFormatProvider formatProvider)
   at SuMo.Common.Service.CommonStartup.CommonConfigure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
   at SuMo.ClassicImport.Service.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at SuMo.ClassicImport.Service.Program.Main(String[] args)
```
I will work up a PR for this shortly.

**Comment by Jaben** [comment]
Thanks for the PR -- merged.
